<br /><br />
<div id="view-content">
	<p>View script for controller <b>Index</b> and script/action name <b>delete</b></p>
    <p>Are you sure that you want to delete
        '<?php echo $this->escape($this->album['title']); ?>' by
        '<?php echo $this->escape($this->album['artist']); ?>'
    </p>
    <form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->album['id'] ;?>" />
            <input type="submit" name="del" value="Да" />
            <input type="submit" name="del" value="Нет" />
        </div>
    </form>
</div>